#klg

exporters:
  elasticsearch:
    endpoint: <ELASTICSEARCH_ENDPOINT>
    headers:
      Authorization: "ApiKey token"

  otlphttp/elastic:
    endpoint: <ELASTICSEARCH_APM_ENDPOINT>
    headers:
      Authorization: "ApiKey token"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]
    metrics: 
      receivers: [otlp]
      exporters: [otlp_http/prometheus]
    traces: 
      receivers: [otlp]
      exporters: [otlphttp/elastic]